"""Generate a project overview from Python source files.

Stdlib-only replacement for the previous langgraph-based version.
Usage: python devtest/project_overview.py [--root .] [--output PROJECT_OVERVIEW.md]
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path


IGNORE = {".git", ".venv", "__pycache__", ".mypy_cache", ".pytest_cache", "dist", "build", ".egg-info"}


def _find_py_files(root: Path) -> list[Path]:
    return [
        p for p in root.rglob("*.py")
        if not any(part in IGNORE for part in p.parts)
    ]


def _extract_info(path: Path) -> dict:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception as e:
        return {"file": str(path), "error": str(e)}

    imports: list[str] = []
    classes: list[str] = []
    functions: list[str] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            imports.append(node.module or "")
        elif isinstance(node, ast.ClassDef):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(node.name)

    return {
        "file": str(path),
        "imports": sorted(set(imports)),
        "classes": classes,
        "functions": functions,
    }


def generate_overview(root: Path) -> str:
    py_files = _find_py_files(root)
    lines = [
        "# Project Overview",
        "",
        f"Auto-generated by `devtest/project_overview.py` — scanned {len(py_files)} Python files.",
        "",
        "## Python Modules",
        "",
    ]
    for py_path in py_files:
        info = _extract_info(py_path)
        try:
            rel = str(Path(info["file"]).relative_to(root))
        except ValueError:
            rel = info["file"]
        lines.append(f"### `{rel}`")
        if "error" in info:
            lines.append(f"- Parse error: {info['error']}")
        else:
            lines.append(f"- Classes: {', '.join(info['classes']) or 'none'}")
            lines.append(f"- Functions: {', '.join(info['functions']) or 'none'}")
            lines.append(f"- Imports: {', '.join(info['imports'][:20]) or 'none'}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate project overview from Python sources.")
    parser.add_argument("--root", default=".", help="Root directory to scan.")
    parser.add_argument("--output", default="PROJECT_OVERVIEW.md", help="Output file path.")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    overview = generate_overview(root)
    output_path = Path(args.output)
    output_path.write_text(overview, encoding="utf-8")
    py_count = len(_find_py_files(root))
    print(f"Scanned {py_count} Python files")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()